site_name: OctopusLab
site_url: https://docs.octopuslab.cz
repo_url: https://github.com/octopuslab-cz/docs_octopuslab_cz
repo_name: GitHub
edit_uri: blob/master/docs/
site_description: 'Python, IoT, roboti a já'
site_author: 'OctopusLAB'
copyright: 'CC-BY'
google_analytics: ['UA-171553408-2', 'docs.octopuslab.cz']

nav:
  - 'Úvod': 
      - 'OctopusLAB': index.md
      - 'ESP32': esp32.md
  - 'Instalace':
      - 'Společná část': install.md
      - 'Windows ': install_win.md
      - 'Linux ': install_linux.md
      - 'Mac ': install_mac.md
      - 'uPip ': pip.md
      - 'Rozšíření ': extension.md
      - 'Setup (nastavení)': setup.md
  - 'Tutoriály':
      - 'Tutorial 1 Python ': tutorial1-python.md
      - 'Tutorial 2 Micropython ESP': tutorial2-micropython-esp.md
      - 'Tutorial EDUkit1': tutorial-edukit1.md
      - 'Tutorial EDUkit2': tutorial-edukit2.md
      - 'Tutorial Robot': tutorial-robot.md
      - 'Micropython workshop IoT': ws-iot.md
      - 'Micropython workshop Robot': ws-robot.md
      - 'Upyshell workshop ': ws-upyshell.md
      - 'workshop GAME': ws-games.md
      - 'Python data': ws-python-data.md
  - 'Dokumentace':
      - 'Referenční příručka': basicdoc.md
      - 'Pinouts': pinouts.md
      - 'Pubsub': pubsub.md
      - 'UpyShell': upyshell.md
      - 'Examples - ukázky': examples.md
  - 'Další':
      - 'Class': class.md
      - 'Github ': github.md
      - 'Popis markdown': tutorials-intro.md
      - 'REPL': repl.md
      - 'FTP': ftp.md
      - 'Ampy': ampy.md
      - 'rshell': rshell.md
      - 'Thony': thony.md
      - 'EsPy': espy.md
      - 'Mu': mu.md
      - 'WebServer': webserver.md
      - 'MQTT': mqtt.md
  - 'Projekty':
      - 'EDU-KIT1': proj-edukit1.md
      - 'EDU-KIT2': proj-edukit2.md
      - 'Displeje': displays.md
      - 'IoT': proj-iot.md
      - 'Robot 01': proj-robot01.md
      - 'Hydroponie': proj-hydro.md
      - 'Ostatní projekty': projects.md

theme: readthedocs

extra_css:
    - css/extra.css

markdown_extensions:
  - markdown.extensions.admonition
  # - markdown.extensions.smarty
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  # - pymdownx.extra
  - markdown.extensions.abbr
  - pymdownx.betterem:
      smart_enable: all
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.tables
  # - pymdownx.superfences
  
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
