site_name: OctopusLab
nav:
  - Úvod: index.md
  - Instalace: install.md
  - Referenční příručka: basicdoc.md
  - Projekty: projects.md
  - 'Vybrané projekty': 
      - 'EDU-KIT1': p-edukit1.md
      - 'uPyshell': p-shell.md
      - 'Robot 01': p-robot01.md
  - 'Workshopy / tutoriály':
      - 'Tutorial 1 ': tutorial1.md
      - 'Micropython workshop 1': ws1.md
      - 'Micropython workshop IoT': ws-iot.md
      - 'Tutorial 2 ': tutorial2.md
      - 'Upyshell workshop ': ws-upyshell.md

theme: readthedocs

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  # - pymdownx.extra
  - markdown.extensions.abbr
  - pymdownx.betterem:
      smart_enable: all
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.tables
  # - pymdownx.superfences
  
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
