site_name: OctopusLab
nav:
  - Úvod: index.md
  - Instalace: install.md
  - 'Tutoriály':
      - 'Předmluva ': tutorials-intro.md
      - 'Tutorial 1 Python ': tutorial1-python.md
      - 'Tutorial 2 Micropython ESP': tutorial2-micropython-esp.md
      - 'Tutorial 3 EDUkit1': tutorial3-edukit1.md
      - 'Micropython workshop IoT': ws-iot.md
      - 'Micropython workshop Robot': ws-robot.md
      - 'Upyshell workshop ': ws-upyshell.md
      - 'Github ': github.md
  - 'Dokumentace':
      - 'Referenční příručka': basicdoc.md
  - 'Projekty':
      - 'EDU-KIT1': proj-edukit1.md
      - 'IoT': proj-iot.md
      - 'Robot 01': proj-robot01.md
      - 'Hydroponie': proj-hydro.md
      - 'Ostatní projekty': projects.md

theme: readthedocs

extra_css:
    - css/extra.css

markdown_extensions:
  - markdown.extensions.admonition
  # - markdown.extensions.smarty
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  # - pymdownx.extra
  - markdown.extensions.abbr
  - pymdownx.betterem:
      smart_enable: all
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.tables
  # - pymdownx.superfences
  
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
